### PR TITLE
feat: update to new IPLD API

### PR DESCRIPTION
**Pull request by vmx**
This is part of the Awesome Endeavour: Async Iterators:
https://github.com/ipfs/js-ipfs/issues/1670

Currently it checks out IPLD directly from a branch. The reason is that I'd like to get approval from all users of the new API first, so that I can still make changes while keeping the history clean.

### CODE REVIEW

**Comment by achingbrain** [comment]
Thanks for this, very helpful.

When are you planning on releasing the new IPLD API properly and not via a GH url?

I ask because once it's out I will refactor this module and all the other unix-fs/mfs related ones to remove pull-streams and expose an async API as part of the same Awesome Endeavour.

**Comment by vmx** [comment]
As soon as possible. If I get a thumbsup from you and @alanshaw that the API looks OK, I'll do a release.

**Comment by achingbrain** [comment]
It doesn't look like the README in the [API changes branch](https://github.com/ipld/js-ipld/tree/new-api-impl) has been updated to document the new API, is the latest source of truth still ipld/js-ipld#185 ?

**Comment by vmx** [comment]
@achingbrain Yes https://github.com/ipld/js-ipld/pull/185 is the source of truth, I also updated it.

**Comment by achingbrain** [comment]
Or ipld/js-ipld#190 now, I guess?

**Comment by vmx** [comment]
https://github.com/ipld/js-ipld/pull/190 is the implementation https://github.com/ipld/js-ipld/pull/185 is the API docs update.

**Comment by achingbrain** [comment]
Superseded by #21

**Pull request closed without merging**
